name: "Yarn install and audit"
author: stemys SA
description: "Install Node.js, run yarn install with frozen lockfile and then run yarn audit"
inputs:
  node-version:
    description: "The Node.js version to use (e.g., 24)"
    required: true
  severity:
    description: "Severity levels to fail on (info|low|moderate|high|critical)"
    required: false
    default: "critical"
  skip-audit:
    description: "If true, skip the yarn audit"
    required: false
    default: "false"
  token:
    description: Personal access token (PAT) used to create comment on Pull Request (PR)
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
        cmd: install --frozen-lockfile

    - name: Run yarn audit
      if: inputs.skip-audit == 'false'
      shell: bash
      run: |
        yarn audit > yarn-audit-results.txt || true

    - name: Upload Yarn audit results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: yarn-audit-results
        path: yarn-audit-results.txt
        retention-days: 5

    - name: Set yarn audit results output
      if: |
        github.event_name == 'pull_request' &&
        inputs.skip-audit == 'false'
      id: output-audit-result
      shell: bash
      run: |
        AUDIT_OUTPUT=$(yarn audit --level ${{ inputs.severity }} || true)
        echo "audit-result<<EOF" >> $GITHUB_OUTPUT
        echo "$AUDIT_OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Find Comment
      if: |
        github.event_name == 'pull_request' &&
        inputs.skip-audit == 'false'
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: Yarn Audit
        token: ${{ inputs.token }}

    - name: Create or update comment
      if: |
        github.event_name == 'pull_request' &&
        inputs.skip-audit == 'false'
      uses: peter-evans/create-or-update-comment@v5
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## 🛡️ Yarn Audit – ${{ inputs.severity }} threshold
          
          ${{ steps.output-audit-result.outputs.audit-result }}
          
          ---
          
          📦 **Full report available here:**
          👉 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts
        edit-mode: replace
        token: ${{ inputs.token }}

    - name: Fail if critical dependencies found
      if: inputs.skip-audit == 'false'
      shell: bash
      run: |
        set +e
        yarn audit --groups dependencies --level critical
        AUDIT_EXIT_CODE=$?
        set -e
        
        case $AUDIT_EXIT_CODE in
          0) echo "✅ No vulnerabilities detected." ;;
          2) echo "⚠️ Low vulnerabilities detected." ;;
          4) echo "⚠️ Moderate vulnerabilities detected." ;;
          8) echo "⚠️ High vulnerabilities detected." ;;
          16) echo "❌ Critical vulnerabilities detected." ;;
          *) echo "⚠️ Unexpected exit code: $AUDIT_EXIT_CODE" ;;
        esac
        
        if [[ $AUDIT_EXIT_CODE -ge 16 ]]; then
          exit 1
        fi